language: python

sudo: required
python:
#  - "2.7"
  - "3.4"
before_install:  
  - sudo apt-get install -y tree
  - sudo apt-get install -y rpm
  - sudo apt-get install -y alien
  - sudo apt-get install -y python3-gi
  - sudo apt-get install -y python3-gi-cairo
  - sudo apt-get install -y gir1.2-gtk-3.0
  - sudo apt-get install -y gir1.2-poppler-0.18
    
#  - sudo ls /home/travis/virtualenv/python3.5.2/lib/python3.5
  
install: 
  - pip install flake8 tox  
  - sudo pip install pyinstaller
  - whereis pyinstaller
#  - ls /usr/share
  

script: 
  - nosetests 
  - sudo python build.py
  - ls
  - cd dist 
  - ls
  