language: python

sudo: required
python:
  - "2.7"
  - "3.4"
before_install:  
  - sudo apt-get install -y python-poppler 
  - sudo apt-get install -y rpm
  - sudo apt-get install -y alien
  - sudo apt-get install -y python-gi
  - sudo apt-get install -y python3-gi
  - sudo apt-get install -y gir1.2-gtk-3.0
  
install: 
  - pip install flake8 tox
  - pip install "git+git://github.com/jflesch/paperwork.git#egg=paperwork"

script: 
  - nosetests 

  